FROM python:3.11

RUN apt update && apt install -y build-essential && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir git+https://github.com/asagilmore/dipy.git@parallel_test

RUN pip install scikit-image[optional]

WORKDIR /app

ADD . /app

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "run.py"]

CMD []